version: '3'

services:
 docs:
    image: documents_kit_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./documents_kit:/app/documents_kit:z
    ports:
      - "7000:7000"
    command: /start-docs
